apiVersion: v1
kind: Secret
metadata:
    name: git-ssh-auth
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:bDSywFGobW1QxUpdwmTZhCz+RbRqAf8gArS+KA2/kfZ+t2ulgQ1+JBEIYz9oCl2lq+wvBceBycakvhcPskxFtNzk77t9q6D3YlUQyYDLCWmp3GSlYr8RDSXq4+fDS7vq4eStzUwobcraE9i4tj3eEqfjR5qXWYUtrYMkFtTPmZiFJZ+BKraiwHg3fRIs2apVJ6nvcYRe8PTu092+4EPsl2R02jhxWxBsN7e51Os0/wDE6e4sa+8gOWIt93Lu+AQbcNwdXn6IxwdKaDjgNHc6FrxbqKpXDw8rnfT1Yj1C1eEPkwEoSOIRmlShBIdzUFYdvoKplTlNxtpsup3pzVbT5BzwAoXOvjKnTjbqBDFyzyIN1g2F+GLAjgAOi4FjJG3DUj5mJmMzaoOa7nLqNYXaEqLDI+ofUuegFU7x0lSCDxDnHN0miNtQ+T1MLKy686CUXC7Uf/E4NMLl4G9+8xdsDIXliZhmNtUbBBxH83rCQ3FMqv/pn2njkeH+fW9R3T2z8eLp9NPvbn1r7ZuXlCSTFGBIg3bNmC5OeG27,iv:x5ykw9wtPiz2iauqGSsp+wtdyQd8BHPxA52mDvqQ6XU=,tag:BUL9gqAyZ3W8YnrnGs0Dlg==,type:str]
    known_hosts: ENC[AES256_GCM,data:MP+7nBWObFWcm1t0bHdhvXr1oR3QrnNc3tb9K+UOEirhTDM+WrrXbaeoHakTb/gZfwT8RdrodooOEi5COe2XU8YaeeU6exa3U+yDmi3xKZhL3MgSSB3yRZnuJNnF03UbTaFa7/hZxHh/Y0xHHjwty/Iu+aM7zg3qfdCaoZQ85x4e/zoISlldn0u3RFdfZwCFoEsBW3pmi9Ls/NI/MxsTZxkYBKXktSoY1ZRlo0o/ffRogjVVizq1t7ncU+Q9GV6eERfin7HdVudWGmdQ71koBnMmQMOUQn1XldhQacL3W3ecbWa/wHWTSZajmyvYa+mapxH/7EYVhj9rTAWYd0Sc2+T/17ndgOL8Z1hP5PNNi/SdLMurXUGsX8BLTnfBh9nMh/VG/fjUU8crCTEWUfrnBPJ/BUgIuCEzGFRmIs984cJRRt/4DAhvMhJpEOxjXg1cIa9w3+F6sk8to/kiRojrBs38tVEafiLNATQhkJzayHDYXRVerpI3mZ5Q9K0IXgMkk8kVNYO8qJBi9T1Z83ijvMgKV0IYfBUT7CD8DyMUWbA8U+A7cpU0N4J195jHR0ntAVgIi5jy28dYu19Z98Ho4ifRb0S4zuknxEYRncLELTzod9iz4LSt949m87PetKoQK2agnQsMadSZTPP5fjWmU4DD1v1WxPrwPw0X6PYEPQLFEs/dYRbduLoH4LVEp1baUt98BGARNZmK/lkDcLtK3CL05jRr/9ex4o9Snlitv9xqvd9h3VKaJCmDDg0kDwAFKxWoJ/3TzCftMFmrsHBxGTeyjnjl0LtrhP3SUTj5qPQRFQhg8H1+hJMDuIau1olK/5zI1Mi89wDrYjgf3viR1KVJ1hAkdxdHMIjFtQvvXbINktYJDOsSfbMnzjgVw9fBaUeAhp0Cs5OqPAdXVFHGu4L7nUn7Jzt2FJDhoM5iDD+IXRFmdQ3E3bOptgyXJtqSlzSWqEdcAQmTCiowBzu83iXzkHLmZqRIOhHfczKzaSvJ3hKanfIJsrsPRxCubBAFlLe8XwqC0Yn8Bpeu1J4Z5ZctPVWSoZ49x/+IAqeU6xaglvhXkLEef1ObqihVk1reMAh6kBV76LETQOA=,iv:qGxWWy2jPJZBRwsXtgGW8nOqxqrxfPDTUjvwF3otWLM=,tag:2wznESmxf34IFcI7UoOSVA==,type:str]
sops:
    age:
        - recipient: age1sy6aknmc298xk7le4zms45dd4frq02lh4v30e4v2vaq800yj2u7sspm2pr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYlUvKzhVQWlVUHc4ZmVU
            OUpZOW91VnVoQUhuS3Vxb0RpTU5vT2k2eFRZCjJ0TmwxM1dJUFExTVpMWm1oQzhW
            RlVJaGJxVXBFSEEyV0ovNlNmMlNxTlkKLS0tIFh6UWgxNlFuUXAvYmU2VHZTb29Z
            dGVrb0F2cThiL2RCMldpTW9iZTJtWmMKSuk5FpfZJPenUYQywmslq7brFJXlnLwT
            EUS3L/PzNL2XhwnsTESNqT/Pym1bkMbEhdk0XXNOvUxVAnzaLPtuvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T22:44:54Z"
    mac: ENC[AES256_GCM,data:JRcfe0HavuO+/K1nnDJB0svdtCZOBky88FGqVFxeBK5xMRyObshnFO98VCT33ayxg0n/fUOnWAO6ellGZ5ZiW633NIPS06CRzhxlQi5DLZrUe19hhxR8HTeT970m56GeCht9oCpAwpAGM23A9eeaMeNIJ7XOoxOQJZ4LG5l67XY=,iv:wIqmabUwlQt8uUtOl83I19pmpV9oXCJ44EqTxO/4dZY=,tag:gF25eHHnn4mxTblEmwVwhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
