---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./git-ssh-auth.sops.yaml
  - ./sops-age.sops.yaml
configMapGenerator:
  - name: flux-instance-helm-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
