apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: ssh-auth
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  vaultConnectionRef: vault-connection
  mount: kubernetes
  kubernetes:
    role: rlssh
    serviceAccount: default
    audiences:
      - vault