---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./csi-driver-smb/ks.yaml
  - ./kubernetes-replicator/ks.yaml