---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./csi-driver-smb/ks.yaml
  - ./kubernetes-replicator/ks.yaml