apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-books-conf
  namespace: default
spec:
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn