apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    namespace: kube-system
    server: {{ .Values.dest_server }}
  project: default
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: csi-driver-nfs
    targetRevision: "4.6.0"
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts