---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: livres
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.1.16"
  share: jeanstock
  subDir: Loisir/Loisir/Books/calibre-FR
  onDelete: retain
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1