apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prowlarr-custom
  namespace: default
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn