apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kube-prom-stack-auth
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rlkube-prom-stack
    serviceAccount: kube-prom-stack
    audiences:
      - vault