---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./helmrelease.yaml

# configMapGenerator:
#   - name: csi-driver-smb-helm-values
#     files:
#       - values.yaml=./helm-values.yaml
# configurations:
#   - kustomizeconfig.yaml
