---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./rabbitmq-ingress.yaml
  - ./rabbitmq-auth.yaml
  - ./rabbitmq-secret.yaml

