dest_server : https://kubernetes.default.svc
default_folder_app : localApps
template_transfo_sonarr: '{{- printf "%s" (b64dec (get .Secrets "postgresql/config:b64dump_sonarr")) | quote -}}'
template_transfo_prowlarr: '{{- printf "%s" (b64dec (get .Secrets "postgresql/config:b64dump_prowlarr")) | quote -}}'
template_transfo_radarr: '{{- printf "%s" (b64dec (get .Secrets "postgresql/config:b64dump_radarr")) | quote -}}'


db :
  appName: cnpg-cluster-rw
  namespace: cnpg
  arr_user: jeank
  # TODO send this to vault
  arr_userPass: pdpdpd
  auth_user: auth
  auth_userPass: pdpdpd
  superuserPass: postgres

arr:
  user : jeank
  userPass : pdpdpd

#for PgLoader
loader:
  active: true

#for dump
dump :
  schedule: "*0 0 * * 1"

#for pg restore
init: true

longhorn : false