apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: cnpg
    server: {{ .Values.dest_server }}
  project: default
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
  sources:
    - repoURL: 'https://github.com/rdartus/k3s-argo.git'
      targetRevision: main
      ref: values
    - chart: cloudnative-pg
      targetRevision: "0.20.0"
      repoURL: https://cloudnative-pg.github.io/charts
      helm : 
        valueFiles:
        - $values/jeanKluster/templates/cnpg/cnpg-helm-values.yaml
