apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-cnpg-dumpauthentik
  namespace: cnpg
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"

spec:
  type: kv-v2

  # mount path
  mount: kv-v2

  # path of the secret
  path: postgresql/dump_authentik

  # dest k8s secret
  destination:
    name: pgsql-secret-dumpauthentik
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: cnpg-auth

  transformationRef:
    name: decode-secrets
    namespace: cnpg
