{{- if .Values.longhorn }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: longhorn
    targetRevision: "1.6.0"
    repoURL: https://charts.longhorn.io
    helm : 
      values: |
{{ include "helmValues.longhorn" . | indent 8 }}
{{end}}