{{- if .Values.complexifyCluster }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: authentik-auth
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rlauthentik
    serviceAccount: authentik
    audiences:
      - vault
{{end}}