---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./onlyoffice-auth.yaml
  - ./onlyoffice-secret.yaml
  - ./onlyoffice-secret-db.yaml
configMapGenerator:
  - name: onlyoffice-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
