apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: my-l2-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-pool