apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-headplane
  namespace: database
spec:
  resources:
    requests:
      storage: 128Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn