apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  timeout.reconciliation: 600s
  ga.trackingid: 'UA-105170809-6'
  url: https://cd.apps.argoproj.io
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: fb563b3a8dd7ea52f683
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: argoproj
          teams:
          - argo-cd-admins