---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pc-secret.sops.yaml
  - ./phone-secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: wireguard-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
