apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-authentik-key
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"

spec:
  type: kv-v2

  # mount path
  mount: kv-v2

  # path of the secret
  path: authentik/config

  # dest k8s secret
  destination:
    name: authentik-key-secret
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: authentik-auth