---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./default-auth.yaml
  - ./default-secret.yaml
  - ./idm-auth.yaml
  - ./authentik-secret-db.yaml
  - ./authentik-secret-default.yaml
  - ./authentik-secret-key.yaml
  - ./authentik-secret-redis.yaml
  - ./authentik-secret-smtp.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: authentik-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
