---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gitops-auth.yaml
  - ./gitops-secret.yaml
  - ./helmrelease.yaml
  - ./clusterRoleBinding.yaml
configMapGenerator:
  - name: weave-gitops-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
