---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pg-dump
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 7m
  path: ./kubernetes/apps/database/pg-dump/app
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.instancesStatus.unhealthy.size() == status.instances
      current: status.instancesStatus.healthy.size() == status.instances
  healthChecks:
    - apiVersion: apps/v1
      kind: deployment
      name: vault-agent-injector
      namespace: vault
    - apiVersion: apps/v1
      kind: deployment
      name: traefik
      namespace: network
    - apiVersion: postgresql.cnpg.io/v1
      kind: cluster
      name: cnpg-cluster
      namespace: database
  dependsOn:
    - name: vault-secrets-operator
      namespace: vault
    - name: traefik
      namespace: network
    - name: cnpg
      namespace: database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
