---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/rancher/local-path-provisioner
  ref:
    branch: master
  ignore: |
    # exclude file from deploy dir
    /deploy/chart/**
    /deploy/example-config.yaml   
    /deploy/example-config.yaml   
    /deploy/kustomization.yaml   
    /deploy/provisioner.yaml   
    /deploy/update_image.sh   