apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 12h
  # url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  url: https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/chart/local-path-provisioner/Chart.yaml
  ref:
    branch: main