apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-upsnap
  namespace: network
spec:
  resources:
    requests:
      storage: 128Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn