apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-upsnap-admin
  namespace: network
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "50"

spec:
  type: kv-v2

  # mount path
  mount: kv-v2

  # path of the secret
  path: default/config

# Cible le StatefulSet pour déclencher un reboot automatique à la mise à jour du secret
  rolloutRestartTargets:
    - kind: StatefulSet
      name: upsnap

  # dest k8s secret
  destination:
    name: upsnap-admin
    create: true
    transformation:
      excludeRaw: true          # pas de clé _raw avec tout le JSON
      includes:
        - ^email$
        - ^secpassword$

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: upsnap-auth