apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: dawarich-auth
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rldawarich
    serviceAccount: default
    audiences:
      - vault
