apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-dawarich
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  type: kv-v2
  mount: kv-v2
  path: dawarich/config
  destination:
    name: dawarich-config
    create: true
  refreshAfter: 30s
  vaultAuthRef: dawarich-auth
