apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dawarich-watched-import
  namespace: default
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
