---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: database
resources:
  - ./namespace.yaml
  - ./cnpg/ks.yaml
  - ./pg-dump/ks.yaml
  - ./pg-dump-sync/ks.yaml
  - ./pg-restore/ks.yaml
  - ./pgadmin/ks.yaml
