---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc-all.yaml
  - ./filebrowser-auth.yaml
  - ./filebrowser-secret.yaml
  - ./smb-secret.yaml
  - ./smb-auth.yaml
configMapGenerator:
  - name: filebrowser-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
