---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./loisir-storageClass.yaml
  - ./all-storageClass.yaml
  - ./jeanstock-storageClass.yaml
  - ./conf-storageClass.yaml