---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./books-storageClass.yaml
  - ./books-conf-storageClass.yaml
  - ./livres-storageClass.yaml
  - ./livres-conf-storageClass.yaml
  - ./qbittorrent-conf-storageClass.yaml
  - ./series-storageClass.yaml
  - ./films-storageClass.yaml
  - ./filebrowser-conf-storageClass.yaml
  - ./drive-storageClass.yaml
  - ./dl-storageClass.yaml
