---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./smb-auth.yaml
  - ./smb-secret.yaml
  # - ./sytemRestore.yml
  - ./sytemBackup.yml
configMapGenerator:
  - name: longhorn-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
