apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: scale-auth
  namespace: network
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rlscale
    serviceAccount: default
    audiences:
      - vault