---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cnpg-client-cert
  namespace: cert-manager
spec:
  secretName: cnpg-client-cert
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"  # permit replication
      replicator.v1.mittwald.de/replication-allowed-namespaces: "database,default"  # comma separated list of namespaces or regular expressions
    labels:
      cnpg.io/reload: ""