---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cnpg-client-cert
  namespace: cert-manager
spec:
  secretName: cnpg-client-cert
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io