---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./issuer-staging.yaml
  - ./issuer-prod.yaml
  - ./issuer-zerossl.yaml
  - ./issuer-selfsigned.yaml
  # - ./cnpg-server-secret.yaml
  - ./cnpg-server-cert.yaml
  # - ./cnpg-client-secret.yaml
  - ./cnpg-client-cert.yaml
