---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./issuer-staging.yaml
  - ./issuer-prod.yaml
  - ./issuer-zerossl.yaml
  - ./zerossl-secret-key.yaml
  - ./zerossl-auth.yaml
