apiVersion: v2
description: |
    AppTemplate BJWS : 
name: appTemplate
version: 1.0.0
kubeVersion: ">=1.22.0-0"
keywords:
- appTemplate

maintainers:
- name: rdartus
dependencies:
- name: common
  version: 3.6.1
  repository: https://bjw-s.github.io/helm-charts/