---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dashboard-ingress.yaml
  - ./endelesshIngressRoute.yaml
  - ./middleware-onlyoffice.yaml
  - ./traefik-authentik-bypass.yaml
  - ./traefik-authentik-middleware.yaml
  - ./traefik-certificate.yaml
  - ./traefik-externalingress.yaml
  - ./traefik-externalservice.yaml
  - ./traefik-headscale-udp.yaml
  - ./traefik-plugin-crowdsec.yaml