apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uptime-kuma-conf
  namespace: network
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn