---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: vault
resources:
  - ./namespace.yaml
  - ./vault/ks.yaml
  - ./vault-secrets-operator/ks.yaml
components:
  - ../../components/flux/sops
