---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
spec:
  interval: 30m
  chart:
    spec:
      chart: zitadel
      version: 9.5.0
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: flux-system
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 1
  valuesFrom:
    - kind: ConfigMap
      name: zitadel-helm-values
