---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./zitadel-secret-masterkey.yaml
  - ./vauban-auth.yaml
  - ./vauban-secret.yaml
  - ./superuser-secret.yaml
configMapGenerator:
  - name: zitadel-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
