apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zitadel.self-tls
  namespace: default
spec:
  dnsNames:
  - zitadel.zitadel.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned
  secretName: zitadel.self-tls
  usages:
  - digital signature
  - key encipherment