---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authenthik.yaml
  - ./bjw-s.yaml
  - ./cnpg.yaml
  - ./crowdsec.yaml
  - ./csi-driver-nfs.yaml
  - ./hashicorp.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./metallb.yaml
  - ./prometheus-community.yaml
  - ./traefik.yaml
  - ./wiremind.yaml
