apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: traefik-auth
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rlzerossl
    serviceAccount: traefik
    audiences:
      - vault