apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "-99"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

spec:
  hostnames:
    - traefik2.dartus.fr
  parentRefs:
    - name: traefik-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: api@internal
          kind: TraefikService