---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vault-secrets-operator
  namespace: &namespace vault
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/vault/vault-secrets-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 15m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vault-secrets-operator-resources
  namespace: &namespace vault
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # healthCheckExprs:
  #   - apiVersion: vault-secrets-operator.io/v1
  #     kind: ClusterIssuer
  #     failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
  #     current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 30m
  path: ./kubernetes/apps/vault/vault-secrets-operator/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 15m
  wait: true