---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./vault-secret.sops.yaml
  - ./vault-config.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: vault-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
