---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: observability
resources:
  - ./namespace.yaml
  - ./kube-prometeus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./kromgo/ks.yaml
components:
  - ../../components/flux/sops
