{{- if .Values.complexifyCluster }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-auth
  namespace: default
data:
  config_local.py: |-
    import os
    
    MASTER_PASSWORD_REQUIRED = True
    AUTHENTICATION_SOURCES = ['oauth2', 'internal']
    OAUTH2_AUTO_CREATE_USER = True
    OAUTH2_NAME=Authentik

    OAUTH2_CONFIG = [
      {
          'OAUTH2_NAME': 'Authentik',
          'OAUTH2_DISPLAY_NAME': 'Authentik',
          'OAUTH2_CLIENT_ID': os.environ['OAUTH2_CLIENT_ID'],
          'OAUTH2_CLIENT_SECRET': os.environ['OAUTH2_CLIENT_SECRET'],
          'OAUTH2_TOKEN_URL': 'https://authentik.dartus.fr/application/o/token/',
          'OAUTH2_AUTHORIZATION_URL': 'https://authentik.dartus.fr/application/o/authorize/',
          'OAUTH2_API_BASE_URL': 'https://authentik.dartus.fr/',
          'OAUTH2_SERVER_METADATA_URL': 'https://authentik.dartus.fr/application/o/pgadmin/.well-known/openid-configuration',
          'OAUTH2_SCOPE': 'openid email profile',
          'OAUTH2_SERVER_METADATA_URL': '',
          'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
          'OAUTH2_ICON': 'fa-google',
          'OAUTH2_BUTTON_COLOR': '#0000ff',
      }
    ]

{{end}}