apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argocd

spec:
  rules:
    - host: argo.dartus.fr
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              - name: argocd-server
                port: 80