---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./trek-auth.yaml
  - ./trek-secret.yaml
  - ./pvc-trek.yaml
  - ./pvc-trek-uploads.yaml

configMapGenerator:
  - name: trek-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
