---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: flux-system
resources:
  # Flux-Kustomizations
  - ./flux-operator/ks.yaml
components:
  - ../../components/flux/sops
