# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: database
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"

spec:
  instances: 2
  certificates:
    serverTLSSecret: cnpg-server-cert
    serverCASecret: cnpg-server-cert
    clientCASecret: cnpg-client-cert
    replicationTLSSecret: cnpg-client-cert
  # imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"


  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  superuserSecret:
    name: superuser-secret

  managed:
    roles:
    - name: arr
      connectionLimit: -1
      inherit: true
      ensure: present
      comment: "*arr user"
      login: true
      passwordSecret:
        name: arr-secret
    - name: auth
      connectionLimit: -1
      inherit: true
      ensure: present
      comment: authentik user 
      passwordSecret:
        name: auth-secret
      login: true
    - name: tand
      connectionLimit: -1
      inherit: true
      ensure: present
      comment: tandoor user 
      login: true
      passwordSecret:
        name: tand-secret
    - name: vauban
      connectionLimit: -1
      inherit: true
      ensure: present
      comment: zitadel user 
      login: true
      passwordSecret:
        name: vauban-secret
    - name: mich
      connectionLimit: -1
      inherit: true
      ensure: present
      comment: immich user - needs admin for backup 
      login: true
      superuser: true
      passwordSecret:
        name: mich-secret2
    - name: onlyoffice
      connectionLimit: -1
      inherit: true
      ensure: present
      comment: onlyoffice user
      login: true
      passwordSecret:
        name: office-secret

  bootstrap:
    initdb:
      database: default
      owner: potgres
      secret:
        name: pgsql-secret
      postInitSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;

  # env:
  #   - name: LD_PRELOAD
  #     value: ""

  # Require 1Gi of space
  storage:
    size: 1Gi