---
defaultPodOptions:
  automountServiceAccountToken: true

controllers:
  main:
    enabled: true
    type: cronjob
    cronjob:
      concurrencyPolicy: Replace
      timeZone: "Europe/Paris"
      schedule: "20 15 * * *"
      startingDeadlineSeconds: 30
      successfulJobsHistory: 1
      failedJobsHistory: 1
      backoffLimit: 6

    containers:
      main:
        image:
          repository: ghcr.io/rdartus/automate-wx
          tag: latest@sha256:2836d6f944750adc46b56508d5cd079ce41b63533ca8fa883dce646cbddb7413
          pullPolicy: IfNotPresent

        env:
          USER_WX:
            valueFrom:
              secretKeyRef:
                name: wx-secret
                key: username
          PASSWORD_WX:
            valueFrom:
              secretKeyRef:
                name: wx-secret
                key: password
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi

persistence:

  config:
    enabled: true

    type: secret
    name: list.json