---
defaultPodOptions:
  automountServiceAccountToken: true

controllers:
  main:
    enabled: true
    type: cronjob
    cronjob:
      concurrencyPolicy: Replace
      timeZone: "Europe/Paris"
      schedule: "40 17 * * *"
      startingDeadlineSeconds: 30
      successfulJobsHistory: 1
      failedJobsHistory: 1
      backoffLimit: 6

    containers:
      main:
        image:
          repository: ghcr.io/rdartus/automate-wx
          tag: latest@sha256:604bd07dcf4176a81e5e1a1937ef3cfc2bccc5804312c7fe478be3d8eed329c3
          pullPolicy: IfNotPresent

        env:
          USER_WX:
            valueFrom:
              secretKeyRef:
                name: wx-secret
                key: username
          PASSWORD_WX:
            valueFrom:
              secretKeyRef:
                name: wx-secret
                key: password
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi

persistence:

  config:
    enabled: true

    type: secret
    name: list.json