---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./wx-secret.yaml
  - ./wx-auth.yaml
  - ./book-secret.yaml
configMapGenerator:
  - name: automate-wx-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
