apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-config
  namespace: default
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn