---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-replicator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: kubernetes-replicator
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kubernetes-replicator-helm-values
