apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kube-prom-stack-auth
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rlkubeprom
    serviceAccount: default
    audiences:
      - vault