---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./observability-auth.yaml
  - ./kube-prom-stack-secret-conf.yaml
configMapGenerator:
  - name: kube-prometheus-stack-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
