---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ssh-auth.yaml
  - ./ssh-secret.yaml
  - ./psql-superuser-secret.yaml
  - ./psqlg-auth.yaml
configMapGenerator:
  - name: pg-restore-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
