apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: ssh-auth
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rlssh
    serviceAccount: default
    audiences:
      - vault