apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: pgsql-auth
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rlpgsql
    serviceAccount: default
    audiences:
      - vault