---
defaultPodOptions:
  automountServiceAccountToken: true
securityContext:
  supplementalGroups:
    - 44   # Groupe video standard
    - 109  #
    - 104

controllers:
  main:
    enabled: true
    type: cronjob
    cronjob:
      concurrencyPolicy: Replace
      timeZone: "Europe/Paris"
      schedule: "0 6 * * *"
      startingDeadlineSeconds: 30
      successfulJobsHistory: 1
      failedJobsHistory: 1
      backoffLimit: 6

    containers:
      main:
        image:
          repository: ghcr.io/rdartus/automate-wx
          tag: latest@sha256:8a065ba321388095a2b352edb661d3fa3c9ad25c4cc641f23d43af59a051d3ae
          pullPolicy: IfNotPresent

        env:
          USER_WX:
            valueFrom:
              secretKeyRef:
                name: wx-secret
                key: username
          PASSWORD_WX:
            valueFrom:
              secretKeyRef:
                name: wx-secret
                key: password
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi

persistence:
  gpu:
      enabled: true
      type: hostPath
      hostPath: /dev/dri/renderD128
      globalMounts:
        - path: /dev/dri/renderD128
  config:
    enabled: true

    type: secret
    name: list.json