apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: auth-role-operator
    serviceAccount: default
    audiences:
      - vault