---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app local-path-provisioner
  namespace: &namespace longhorn-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: ./deploy/local-path-storage.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 30m
  wait: true