apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - github.com/metallb/metallb/config/frr?ref=v0.13.12
  - base/addresspools.yaml
  - base/L2Advertisement.yaml

patches:
  - path: overlays/production/ip-adresspool.yaml
  - path: overlays/production/bgppeers.yaml
