{{-  $dbServiceName := printf "%s.%s.svc.cluster.local" .Values.db.appName .Values.db.namespace -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: default
    server: {{ .Values.dest_server }}
  project: default
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: prowlarr
    targetRevision: "*"
    repoURL: https://k8s-home-lab.github.io/helm-charts/
    helm : 
      values: |

        #
        # IMPORTANT NOTE
        #
        # This chart inherits from our common library chart. You can check the default values/options here:
        # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
        #

        image:
          # -- image repository
          repository: ghcr.io/onedr0p/prowlarr
          # @default -- chart.appVersion
          tag: rolling
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables.
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          PROWLARR__AUTHENTICATION_METHOD: "External"
          PROWLARR__POSTGRES_HOST: {{ $dbServiceName }}
          PROWLARR__POSTGRES_MAIN_DB: 'prowlarr-main'
          PROWLARR__POSTGRES_LOG_DB: 'prowlarr-log'
          PROWLARR__POSTGRES_USER: {{ .Values.db.user }}
          PROWLARR__POSTGRES_PASSWORD: {{ .Values.db.userPass }}

        # -- Configures service settings for the chart.
        # @default -- See values.yaml
        service:
          main:
            ports:
              http:
                port: 9696


        ingress:
          # -- Enable and configure ingress settings for the chart under this key.
          # @default -- See values.yaml

          main:
            enabled: true
            annotations:
              hajimari.io/enable: "true"
              hajimari.io/group: "Media"
              hajimari.io/icon: "mdi:CogPlayOutline"
            hosts:
              -  # -- Host address. Helm template can be passed.
                host: prowlarr.dartus.fr
                ## Configure the paths for the host
                paths:
                  -  # -- Path.  Helm template can be passed.
                    path: /
                    # -- Ignored if not kubeVersion >= 1.14-0
                    pathType: Prefix


        # -- Configure persistence settings for the chart under this key.
        # @default -- See values.yaml
        persistence:
          config:
            enabled: false