apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mealie-media
  namespace: default
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn