apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: tailscale-state-backup
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault-backend
      kind: SecretStore
  selector:
    secret:
      name: tailscale-state
  updatePolicy: Replace
  data:
    - match:
        secretKey: ""
        remoteRef:
          remoteKey: scale/state