apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tailscale
  namespace: database
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn