apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: network
spec:
  provider:
    vault:
      server: "https://vault.dartus.fr"
      path: "kv-v2"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "rleso-tailscale"
          serviceAccountRef:
            name: tailscale-eso
            audiences:
              - vault