apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-tailscale-secret
  namespace: network
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  type: kv-v2
  # Même point de montage et chemin que ton secret principal
  mount: kv-v2
  path: scale/state

  destination:
    # Nom du nouveau secret Kubernetes qui sera créé
    name: tailscale-state
    create: true
    # Le bloc transformation permet de filtrer et mapper les clés
    transformation:
      # EXCLUT toutes les clés existantes dans Vault de la copie par défaut
      excludes:
        - ".*"
      #   - "tailscale_device_ips"
      #   - "tailscale_device_id"
      #   - "tailscale__profiles"
      #   - "tailscale_profile-2253"
      #   - "tailscale_tailscale_capver"
      
      # # On les recrée manuellement en forçant la conversion en chaîne de caractères
      # templates:
      #   tailscale_device_ips:
      #     text: '{{- get .Secrets "tailscale_device_ips" | toJson -}}'
      #   tailscale__profiles:
      #     text: '{{- get .Secrets "tailscale__profiles" | toJson -}}'
      #   tailscale_profile-2253:
      #     text: '{{- get .Secrets "tailscale_profile-2253" | toJson -}}'
      #   tailscale_device_id:
      #     text: '{{- get .Secrets "tailscale_device_id" | toString -}}'
      #   tailscale_tailscale_capver:
      #     text: '{{- get .Secrets "tailscale_tailscale_capver" | toString -}}'

  refreshAfter: "1h"
  vaultAuthRef: scale-auth

  # Optionnel : Ajoute ici les workloads à redémarrer si la clé change
  rolloutRestartTargets:
    - kind: StatefulSet
      name: vpn