apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-tailscale-secret
  namespace: network
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  type: kv-v2
  # Même point de montage et chemin que ton secret principal
  mount: kv-v2
  path: scale/state

  destination:
    # Nom du nouveau secret Kubernetes qui sera créé
    name: tailscale-state
    create: true
    # Le bloc transformation permet de filtrer et mapper les clés
    transformation:
      # # EXCLUT toutes les clés existantes dans Vault de la copie par défaut
      # excludes:
      #   - ".*"
      # templates:
      #   # Clé dans le secret k8s : Valeur extraite du secret Vault
      #   tailscale-state:
      #     text: '{{ get .Secrets "tailscale-state" }}'

  refreshAfter: "30s"
  vaultAuthRef: scale-auth

  # Optionnel : Ajoute ici les workloads à redémarrer si la clé change
  rolloutRestartTargets:
    - kind: StatefulSet
      name: vpn