---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./immich-secret.yaml
  - ./immich-db-secret.yaml
  - ./immich-auth.yaml
  - ./pvc-photo.yaml
  - ./pvc-ml-cache.yaml
configMapGenerator:
  - name: immich-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
