apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photo
  namespace: default
spec:
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn