apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tandoor-media
  namespace: default
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn