apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  generation: 3
  name: back-job
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 2 */5 * *
  groups: []
  labels: {}
  name: Back-job
  parameters:
    full-backup-interval: "15"
  retain: 15
  task: backup