apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-to-migrate
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
  selector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - pirate