
apiVersion: batch/v1
kind: Job
metadata:
  name: pgloader-migrate
  annotations:
  argocd.argoproj.io/hook: Sync
  argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      volumes: 
      - name: db-storage
        persistentVolumeClaim:
          claimName: pvc-db-to-migrate
      containers:
      - name: pgloader
        volumeMounts:
        - mountPath: /db
          name: db-storage
        image: ghcr.io/rdartus/pgloader
        command:
        - /bin/sh
        - -c
        - |
          PGPASSWORD={{.Values.db.userPass}} psql -h {{.Values.db.appName}}.{{.Values.db.namespace}}.svc.cluster.local -U {{.Values.db.user}} -d prowlarr-main -f /db/rm_prowlarr 
          PGPASSWORD={{.Values.db.userPass}} psql -h {{.Values.db.appName}}.{{.Values.db.namespace}}.svc.cluster.local -U {{.Values.db.user}} -d radarr-main -f /db/rm_radarr
          PGPASSWORD={{.Values.db.userPass}} psql -h {{.Values.db.appName}}.{{.Values.db.namespace}}.svc.cluster.local -U {{.Values.db.user}} -d sonarr-main -f /db/rm_sonarr
          pgloader --with "quote identifiers" --with "data only" --with "prefetch rows = 100" --with "batch size = 1MB" /db/radarr.db 'postgresql://{{.Values.db.user}}:{{.Values.db.userPass}}@{{.Values.db.appName}}.{{.Values.db.namespace}}.svc.cluster.local/radarr-main' || true
          pgloader --with "quote identifiers" --with "data only" /db/prowlarr.db 'postgresql://{{.Values.db.user}}:{{.Values.db.userPass}}@{{.Values.db.appName}}.{{.Values.db.namespace}}.svc.cluster.local/prowlarr-main' || true
          pgloader --with "quote identifiers" --with "data only" --with "prefetch rows = 100" --with "batch size = 1MB" /db/sonarr.db 'postgresql://{{.Values.db.user}}:{{.Values.db.userPass}}@{{.Values.db.appName}}.{{.Values.db.namespace}}.svc.cluster.local/sonarr-main' || true
          
      restartPolicy: Never
      # affinity:
      #   nodeSelector:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: kubernetes.io/hostname
      #         operator: In
      #         values:
      #         - pirate
  backoffLimit: 0