apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hajimari-ingress
  namespace: hajimari

spec:
  className: traefik-ingresses
  defaultBackend:
    service:
      name: hajimari
      port: 3000