---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: network
resources:
  - ./namespace.yaml
  - ./traefik/ks.yaml
  - ./crowdsec/ks.yaml
  - ./ddns-updater/ks.yaml
  - ./wireguard/ks.yaml
  - ./headscale/ks.yaml
  - ./metallb/ks.yaml
  - ./tailscale/ks.yaml
components:
  - ../../components/flux/sops
