apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: s3-auth
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rlS3
    serviceAccount: velero
    audiences:
      - vault